name = "Qoonautics"
version = "v0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f8ee3da52f07e97d47232af68a786cb1ff70eedd936ec327183290d57b78613"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
