name = "Qoonautics"
version = "v0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb03efc82c706bdd1fab6b62cf10a4062cce37f3267540c6a4ba3de372dd8978"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
