name = "Qoonautics"
version = "v0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e50cc8b03dc53f6f3834ed0a395856571ee54d0764f0e718df3674b901fa330"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
